### ISSUE TITLE
Problema grave no README

### ISSUE THREAD

**Issue by rodrigo-borges** [CinthiaS/mv-text-summarizer#2]
## Descrição do problema

Nos passos 4. e 5. do README está escrito "matrixes" e isso está me impedindo de concluir o setup.

## Sugestão de solução

Longe de mim sugerir uma melhoria num repositório de conteúdo tão avançado, mas se fosse arriscar um palpite eu diria para substituir por "matrizes".

**Comment by CinthiaS** [comment]
README was updated
